apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-temperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversor-temperatura
  template:
    metadata:
      labels:
        app: conversor-temperatura
    spec:
      containers:
      - name: app
        image: felipecs8/conversor-temperatura:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5